<?php

/**
 * @file
 * The reset password module.
 */

use Drupal\Component\Utility\Crypt;
use Drupal\Core\Site\Settings;
use Drupal\user\UserInterface;

/**
 * Creates a unique hash value for use in per-user URLs.
 */
function reset_password_user_pass_rehash(UserInterface $account, $timestamp): string {
  $data = $timestamp;
  $data .= $account->id();
  $data .= $account->getEmail();
  return Crypt::hmacBase64($data, Settings::getHashSalt() . $account->getPassword());
}
